### ISSUE TITLE
Property 'd' does not exist on type 'Spacetime'

### ISSUE THREAD

**Issue by jaipresto** [spencermountain/spacetime#131]
Only started after updating to 5.8.0, though I think it may have been missing for ~20 days (when the main types file was last updated). 

Is this intentional? 

I've fixed it temporarily (I use it in quite a lot of places) by adding
```  typescript
/** @returns the date as a native date object */
 d: Date
```
back to into the Spacetime interface.

So:

``` typescript
...

export interface Spacetime extends SpacetimeMain, SpacetimeGetterSetters, SpacetimeUtils {

  /** @returns the date as a native date object */
  d: Date

  /** @returns epoch in milliseconds */
  epoch: number

  /** @returns whether warnings are enabled */
  silent: boolean

  /** @returns the timezone tz database name, eg, 'america/denver'  */
  tz: string

  /** @returns the tz database nameset  */
  timezones: TimezoneSet
}
```

**Comment by spencermountain** [comment]
oh, are you getting a typescript runtime error?
yeah sorry, `.d` was originally supposed to be an internal method, but it's actually kinda useful, isn't it.

we should add it back to the types, for sure then
thanks

**Comment by jaipresto** [comment]
haha yes - I use it server and client-side.

And yes, ts runtime errors.
